### ISSUE TITLE
Database Schema issue

### ISSUE THREAD

**Issue by akamdar** [eroberer/Restoraunt-Application-WebServices-NodeJS#1]
Hi @eroberer ,

Can you please provide the database schema. 

What all fields are required for the different tables? Is there any POST api for user registration ? I didn't get in the code.

**Comment by eroberer** [comment]
Hi @akamdar,

i have inserted db tables
[restoran.sql](https://github.com/eroberer/Restaurant-Application-WebServices-NodeJS/blob/master/restoran.sql)

This project hasn't got user operations, because there were user operations in other project.

**Comment by akamdar** [comment]
Thanks a lot @eroberer.
